site_name: cantina

theme: material

nav:
    - Quienes somos: index.md
    - Desayuno: desayuno.md
    - Menú de medio día: comida.md
    - Menú de noche: cena.md
    - Más información: info.md 


include_search_page: true
copyright: Esta web ha sido realizada por Sergio Grima Bravo. Reservados todos los derechos de autor.