site_name: cantina

theme: material

nav:
    - La Cantina Pedralbes: index.md
    - Desayuno: desayuno.md
    - Menú de medio día: comida.md
    - Menú de noche: cena.md
    - About: about.md 

extra:
    social:
        - icon: fontawesome/brands/instagram 
        - icon: fontawesome/brands/twitter
        - icon: fontawesome/brands/github


include_search_page: true
copyright: Esta web ha sido realizada por Sergio Grima Bravo. Reservados todos los derechos de autor.